### ISSUE TITLE
6.1.b workaround codepen inadvertently has flex-grow: 1 instead of flex-shrink: 1

### ISSUE THREAD

**Issue by sg00dwin** [philipwalton/flexbugs#100]
I believe the 6.1.b workaround should set .FlexItem to ```flex-shrink:1``` instead of ```flex-grow:1```

6.1.b — workaround
http://codepen.io/philipwalton/pen/azBrLo

**Comment by philipwalton** [comment]
Thanks! I've updated the pen.
