### ISSUE TITLE
"display:-webkit-box;" causes issue in newer version of Safari

### ISSUE THREAD

**Issue by kristianwithak** [philipwalton/flexbugs#102]
From what I can gather, this set of rules present on `.row`:

```
display:-webkit-flex;
display:-ms-flexbox;
display:-webkit-box;
display:flex;
```

...causes issues in newer version of safari. Here's the details...

I'm viewing a site using flexbox grid in Safari 9.

Because safari ignores the `display:flex;` rule, it falls back to `display:-webkit-box`. But, since that rule is specific to older versions of safari, it does nothing.

Yet, even though it does nothing, the browser doesn't continue to fall back to the `display:-webkit-flex` declaration... so the elements with class `.row` remain "unflexed".

I suspect the fix is to simply re-order the rules like so...

```
display:-webkit-box;
display:-webkit-flex;
display:-ms-flexbox;
display:flex;
```

**Comment by philipwalton** [comment]
I'm not sure where you got that code from, but it's not anywhere on the Flexbugs README, so I'm not sure it has anything to do with this repo.

You're correct that ordering flexbox fallback that way could cause issues, but that's an implementation concern, not a flexbox concern.

**Comment by kristianwithak** [comment]
I'm so sorry... I don't know how, but I ended up creating this issue in entirely the wrong repository. My mistake!
