### ISSUE TITLE
Height/Scroll problem on IPad/IPhone Safari

### ISSUE THREAD

**Issue by Brunomachadob** [philipwalton/flexbugs#106]
I have a page with body and html with **height: 100%**, and then nested flex containers.
My flex config is **grow:1**, **shrink:1** and **base:0**.
The last childs of this containers has a fixed huge height, forcing scroll on the page, but only on IPad/Iphone Safari the scroll doesn't happen.
I tested on **Windows/Chrome**, **Windows/FF**, **Windows/IE**, **Mac/Safari**, all these browsers works fine.
Who is wrong? Me or the browser? haha

Here is the [plunker](http://plnkr.co/edit/CU4h5aciAmYfwv28fDch?) used for tests.

Thanks in advance

**Comment by jpdevries** [comment]
I converted your plunker to a codepen that uses autoprefixer:
http://codepen.io/jpdevries/pen/YwPRgL?editors=110

scrolling works in iOS Safari in the codepen for me

**Comment by philipwalton** [comment]
I also do not see a problem on iOS Safari, so I'm going to close this. If you think there's still an issue, please go into more detail on how to reproduce it.

**Comment by johnunclesam** [comment]
http://stackoverflow.com/questions/43175481/different-behavior-of-flexbox-with-overflow-y-scroll-on-safari-firefox-and-ed

I have similar problem here. Safari doesn't overflow!!
