### ISSUE TITLE
Nested flex container – text-align

### ISSUE THREAD

**Issue by verpixelt** [philipwalton/flexbugs#107]
`text-align` (in that case `center`) stops working if you start nesting flex containers e.g. http://codepen.io/verpixelt/pen/vLNymo
If you remove `display: flex` from the flex children (line: 40), `text-align: center` works as expected.
Either I overlook something or this is really a bug. Happy to hear your feedback.

**Comment by philipwalton** [comment]
`text-align` is working fine in your example. The problem is that the `<div>` wrapping the text itself is aligned to the left because it's a flex item. If you inspect the element in your example with the developer tools you should be able to see what's going on.

**Comment by verpixelt** [comment]
It works, if I set `width: 100%` on the mentioned `div`. I was under the impression, that even if `display: flex` is applied on a flex-child it would act like a block level element and automatically occupy the whole available width.

**Comment by philipwalton** [comment]
If an element is a flex item, then its size is governed by the result of the flex layout algorithm. It's not just going to be 100% wide by default.
