### ISSUE TITLE
[Chrome Safari]Transparent backgrounds painting doesn't respect "order" property

### ISSUE THREAD

**Issue by yisibl** [philipwalton/flexbugs#110]
https://code.google.com/p/chromium/issues/detail?id=561999

> The very same issue can be reproduced in Grid Layout and Flexbox.
If 2 items overlap, the backgrounds are painted following "order" property (order-modified document order).
However if the items are transparent ("opacity: 0.5;") the order of the backgrounds is wrong.

> Attached example to reproduce the issue. Two first cases (Grid and Flex) use "order" to modify the DOM order and the transparent background is wrong. The next 2 cases change the DOM order to show the exampled result.
Check it live at: http://jsbin.com/rawedo/1/edit?html,css,output

> FWIW, we're calling BlockPainter::paintAsInlineBlock() [1] in the very same order in both cases. For grid layout code we do it at GridPainter::paintChildren() [2].
However, it seems that BlockPainter::paintAsInlineBlock() is not enough for this case.
Dunno if BlockPainter::paintAsInlineBlock() needs to do something more, or if we need deeper changes.

> [1] https://chromium.googlesource.com/chromium/src/+/d8eabbd3851a266cc42a6556ed05c79cfda30166/third_party/WebKit/Source/core/paint/BlockPainter.cpp#125
[2] https://chromium.googlesource.com/chromium/src/+/d8eabbd3851a266cc42a6556ed05c79cfda30166/third_party/WebKit/Source/core/paint/GridPainter.cpp#79  
![test](https://chromium.googlecode.com/issues/attachment?aid=5619990000001&name=css-grid-css-flex-transparent-background-order.png&token=ABZ6GAfww6emPp4d6FD6_ZnRfTX6g_NajQ%3A1450318735254&id=561999&mod_ts_token=ABZ6GAfC_EqDyXTC-yurqDZkXEQVV7YXuw%3A1450318735254&inline=1)

**Comment by philipwalton** [comment]
Thanks, but unless a bug has a workaround, I'm hesitant to include it in the README. There are *tons* of reported flexbox bugs on browser issue trackers, and it would be unrealistic to include them all here.

This repo tries to focus on common bugs with future-friendly workarounds.
