### ISSUE TITLE
[Firefox][IE] Different behaviour from Chrome to IE and Firefox when an element is absolute posiitoned

### ISSUE THREAD

**Issue by marcofugaro** [philipwalton/flexbugs#111]
I've noticed some weird stuff happening, probably it has been noticed before, but I suppose this could help you and also help me.

I have some flex elements, when I give the first one a `position: absolute;` intuitively it is removed from the flex flow, but this happens only on Chrome! On Firefox and IE the element is treated as a 0 width flex element.

[Here is a demo of what I'm talking about](http://codepen.io/marco_fugaro/pen/rVabBJ)

**Solution**: `margin-left: auto;` to the second child

**Comment by philipwalton** [comment]
Adding `margin-left: auto` doesn't fix the problem in your example (at least not in Firefox). It pushes the second item to the end.

While I agree this is a bug, I can't think of a good workaround other than to recommend not using absolutely position flex items (which is honestly what I'd recommend in general).

Do you know if there's a Firefox or IE bug for this already? If not I'd recommend reporting it and replying here with the links. For know I'm going to close the issue, but feel free to reopen if you think of a good workaround.

**Comment by marcofugaro** [comment]
@philipwalton you're right, the workaround worked last year when I encountered the bug. No I can't find a good workaround now.

I dug around bugzilla and didn't find anything similar, will try to submit an issue of this later!

**Comment by philipwalton** [comment]
For anyone looking, the FF tracking bug for this is here:
https://bugzilla.mozilla.org/show_bug.cgi?id=874718

**Comment by ChloeFl** [comment]
I am facing a lookalike problem currently on Firefox 52 and came across this topic on stackoverflow : http://stackoverflow.com/questions/42698493/how-does-the-order-property-work-on-absolutely-positioned-children-of-a-flex-con

where an explanation and a workaround were found : 

> [...] browser makers have significant discretion in implementing this feature. And it appears that the major browsers have not even begun implementation

> I don't consider this a legitimate solution, but if I add position:absolute with some javascript after the page loads instead of it being in the css file, order works as expected -  answered Mar 9 at 15:37 Michael_B

For anyone who comes across this issue here.
