### ISSUE TITLE
display: table-cell in flex container bug

### ISSUE THREAD

**Issue by yisibl** [philipwalton/flexbugs#113]
* https://code.google.com/p/chromium/issues/detail?id=243056
* https://lists.w3.org/Archives/Public/www-style/2015Sep/0038.html 

Test: http://people.mozilla.org/~dholbert/tests/flexbox/compat_tests/table-cell-in-flex-container-1.html

**Comment by philipwalton** [comment]
I'm closing this for the same reason as in #110. Feel free to reopen if you think there's a point I've missed.
