### ISSUE TITLE
[Chrome] Percentage-based sizing doesn't work in flex item child elements

### ISSUE THREAD

**Issue by paulojreis** [philipwalton/flexbugs#115]
I've noticed that - in Chrome - child elements of a flex item can't assume a height value of e.g. 100%, in order to fill the height of their parent. Flex items assume the height of their `display: flex` parents without a problem (and this is a typical demo of flexbox: equal-height columns), but I can't *take* that assumed height to their children by giving them `height: 100%` This is a known issue in Chrome.

Assume:
* A given elements (**row**) with `display: flex`;
* Two elements (**col**) which are child elements of **row** (i.e. **col** elements are flex items);
* Two elements (**content**), one inside each element **col** , with `height: 100%`.

I'd expect that the **content** elements would be expanded (because of the `height: 100%` setting), filling the full height of their parents (**col**, which already fill their parent **row** height). However, they behave as if their `height` was defined with the default value of `auto` (i.e. they only take as much height as they need). I get the expected behaviour in Firefox and Internet Explorer, but no luck in Chrome.

Test case available at https://jsfiddle.net/vLw71566/1/

Bug already tracked in Chromium, at https://code.google.com/p/chromium/issues/detail?id=346275.

P.S. Although I'm reporting this as a *flexbug*, bear in mind that the spec isn't crystal clear on the subject: http://www.w3.org/TR/css-flexbox-1/#definite-sizes. It's arguable that Chrome's implementation is the most spec-compliant (albeit less useful for developers).

**Comment by LPGhatguy** [comment]
Unless the **col** elements have a definite cross size, what would the size be of the **content** elements? Intuitively, I would think they should the size of the largest **content** element's cross size, but that's an indefinite measure.

I don't see how the height of **row** or **col** could be determined without measuring content and taking the max of the row for a given `align-items: stretch` flex container.

**Comment by paulojreis** [comment]
If I understood correctly: the behaviour you intuitively expect seems to be what Firefox and Internet Explorer are doing, right?

**Comment by LPGhatguy** [comment]
That's what I would hope, but I'm under the impression that it depends on an indefinite size. I have a feeling that the developers commenting on the Chromium bug tracker probably have a better understanding of the specification than I do though.

**Comment by gregwhitworth** [comment]
So this was brought up and Chrome was against this because of the potential perf implications, thus the lack of implementation of this. That said, we discussed it and this was resolved on so hopefully in future versions this will work :)

Here is the resolution [email with the CSSWG](https://lists.w3.org/Archives/Public/www-style/2015Dec/0014.html)
