### ISSUE TITLE
Flexbox bug in IE11: Justify-content: space-around

### ISSUE THREAD

**Issue by hgberman** [philipwalton/flexbugs#117]
I think there might be a bug in IE11.  

Here's what's happening. I am using the CSS declaration "justify-content: space-around" with a single-row flex container. The flex items are too big to be contained within one row of a single-line flex container. According to the Worldwide Web Consortium, we should see the flex items packed, centered, and overflowing the too-small container on both sides. And this is what occurs with Firefox and Chrome.

But it doesn’t work this way with Internet Explorer 11 – at least not on my computer. With Internet Explorer 11, the items start along the left edge of the container and break out of the container only on the right side.

This is not what I was expecting with “justify-content: space-around”, based on the Worldwide Web Consortium specs at https://drafts.csswg.org/css-flexbox/#justify-content-property.  

In case it helps, here's the CSS code and HTML that produced the above results:

[FlexboxBug.docx](https://github.com/philipwalton/flexbugs/files/85228/FlexboxBug.docx)

When I run this code on Firefox or Chrome, it works as described by WW3; with Internet Explorer 11, it does something different.

**Comment by Jesipov** [comment]
IE10 + 11

same with ```justify-content: center```

**Comment by philipwalton** [comment]
Yeah, this is probably a bug, but without a good workaround, listing it here is the best we can do (as the README is for bugs with workarounds only). I'm going to close this issue, but feel free to reopen if you discover a good cross-browser workaround.
