### ISSUE TITLE
Chrome 48 and 49: Nested flex-direction column elements cause incorrect heights

### ISSUE THREAD

**Issue by ChrisBoon** [philipwalton/flexbugs#119]
I'm noticing a number of issues in Chrome 48 and 49 on OSX, Windows, and Android when you nest multiple elements with 'flex-direction: column' and 'flex: 1 1 auto'.

**Failure to reduce height of elements when you reduce window height:**
http://s.codepen.io/chrisboon27/full/wMqwMB 

If you expand the height of your window both inner divs (blue and brown) will expand. However reducing the window height will cause them to stay large and overflow. Adjusting the width of the window causes then to jump back to the height that would fit.

**Unexpected (and wrong) recalculation of height when a repaint occurs**
http://codepen.io/chrisboon27/full/BjdBqL 

In this pen clicking the blue or brown boxes will simply use jquery to adjust its inner orange divs opacity. This causes a repaint at which point Chrome also adjusts the height of the clicked div.
Note that again adjusting the width of the window will fix the problem.

I've viewed the pens in Chrome 48 and 49 on iOS, Windows 10, and Android and the problems occur.
The issues don't appear in the current stable channel (47), only beta, dev, and canary builds, so maybe they'll never appear in stable?

**Comment by ChrisBoon** [comment]
btw I've filed bugs for this:
https://code.google.com/p/chromium/issues/detail?id=576859 
https://code.google.com/p/chromium/issues/detail?id=576855

**Comment by philipwalton** [comment]
Thanks for filing the bugs @ChrisBoon. Since this seems to be a Chrome re-layout/paint issue, it's unlikely a good cross-browser workaround exists for it, so I'm going to close this issue.

If anyone else finds this thread, please watch the bugs linked above for fix status.
