### ISSUE TITLE
IE11 Won't Wrap a Long Text String inside of a Parent with 'display: flex;'

### ISSUE THREAD

**Issue by isralduke** [philipwalton/flexbugs#124]
IE11 exhibits a bug in which a parent element with `display: flex;` won't wrap long amounts of child text. The text overflows the parent. This is discussed in [caniuse.com](http://caniuse.com/#search=flex) in the Known Issues tab. _(I don't think it's a bug you listed.)_

The CodePen entry below offers a workaround. The Bug and Workaround are only visible using IE11. Webkit browsers and FireFox don't have any problem.

http://codepen.io/dukebranding/pen/vLQxGy

The workaround involves placing the non-wrapping child text inside of a `<p>` (but a `<div>` may also work) applying the styles seen below.

```
p {
	display: flex;
	width: 100%;
}
```

Thank you for your list!

**Comment by philipwalton** [comment]
This workaround doesn't work for me using the example cited on caniuse.com:
http://codepen.io/anon/pen/MKLgVY?editors=1100

**Comment by isralduke** [comment]
Others have found weak points in my workaround as well. Thank you for looking.
