### ISSUE TITLE
Addition to workaround for #2 (Column flex items set to align-items:center overflow their container)

### ISSUE THREAD

**Issue by abea** [philipwalton/flexbugs#127]
https://github.com/philipwalton/flexbugs#2-column-flex-items-set-to-align-itemscenter-overflow-their-container

I ran into this IE 11 bug and tried your workaround to set the flex items to `max-width: 100%;`. That didn't work, but oddly enough setting `max-width: 99.9%;` did work. If you've run across instances where 100% didn't work, that might be worth a try.

**Comment by philipwalton** [comment]
Do you have an example?

**Comment by abea** [comment]
Just spent about a half hour trying to reproduce it outside my client's site. When it's launched in the next month or so I'll share here.

**Comment by abea** [comment]
After launching I went back to post the example here, but I'm not seeing the bug now. Closing this until I can reproduce.

**Comment by abea** [comment]
Spoke too soon. The page is https://www.litehousefoods.com/our-brands. The selector is `.site-feature__split > *`, targeting immediate children of this flex parent element. (Inspect one of the logos and go up the DOM to `.text-center`).

In IE11 (Win 8.1 and 10 at least), when that selector has max-width unset or set to 100%, the contents will break out of their parent at the medium break point (1080px - 1400px). If the max width is set to 99.9% or lower, it will not.

![screen shot 2016-03-27 at 10 47 06 am](https://cloud.githubusercontent.com/assets/1155984/14065905/f80c6d26-f409-11e5-8f65-753a737bcc90.png)

**Comment by philipwalton** [comment]
I agree this is strange. I'm not sure it has anything to do with flexbug 2, though. If you remove the `text-align: center` in your example, the problem persists.

My hunch is it's because of the images, but it's hard to say for sure because there's so much going on there. We'd need to have a reduced example before we could make a general recommendation to use `99.9%`.

**Comment by cthedot** [comment]
Seems the fix I tried for #138 does work here too. If I set overflow: hidden for the flex item even with max-width: 100% it works. Actually the 99.9% seems a nice IE11 hack as overflow: hidden might not be great for all layouts if e.g. anything is positioned outside would be cut off too

**Comment by abea** [comment]
I definitely agree there's a lot going on. I tried reducing it down before without much luck, though I might have been retaining the wrong bits. I'm comfortable closing this if you want since the context isn't clear.

**Comment by philipwalton** [comment]
Sounds good. If you remember something, or if someone else wants to try reducing it, we can reopen.
