### ISSUE TITLE
IE11 doesn't apply transition to flex.

### ISSUE THREAD

**Issue by kitsunde** [philipwalton/flexbugs#130]
Demo: https://jsbin.com/muqiwe/2/edit?html,css,output

Latest firefox, chrome, safari will transition the boxes on mouse over. IE11 will simply snap in place.

**Comment by philipwalton** [comment]
Thanks, I think this falls pretty squarely in the realm of progressive enhancement, so I don't know if I'd actually make any recommendation that anyone do anything differently here.

Having this not transition is IE11 shouldn't affect the usability of any app, it just makes it slightly less cool.
