### ISSUE TITLE
Flex-offset does not work until set to 5

### ISSUE THREAD

**Issue by kentonbmax** [philipwalton/flexbugs#131]
There is no flex offset when viewed until a value of 5 is set. You can see this easily by creating a row with 2 columns. Make the columns flex=20 and set there background color to something other than white. View and notice that they are touching. Now set flex 1-4, and view. They touch. Set flex 5, larger than I wanted gap of offset. I'm trying to use this with ng-repeat where there are n number of divs that need to be seperated by an offset of about 5-10px

**Comment by kentonbmax** [comment]
I was curious, can you not set a flex-offset on the layout row div and have all the columns within it apply that offset? appears to not work.

**Comment by kentonbmax** [comment]
Found that padding works well. Please update documentation regarding 33/66 this implies that multiples of .5 will work.

**Comment by philipwalton** [comment]
I'm not sure what you're referring to when you say "flex-offset". That's not a Flexbox property, nor is it mentioned anywhere in this README, so I'm not sure what you're looking at.
