### ISSUE TITLE
Workaround addition to #3

### ISSUE THREAD

**Issue by dan-gamble** [philipwalton/flexbugs#135]
We've found in IE11 you can add `height: 0` to the item that has `min-height: x` and it will make it function correctly. Are there any drawbacks to this?

**Comment by kumarharsh** [comment]
Wow, really! It works for some reason !!! I was **just** debugging this in IE, and working with `height:100%`

**Comment by dan-gamble** [comment]
Only problem i can see with `height: 100%` is you wouldn't need the `min-height` in the 1st place. Having `height: 0` means `min-height` would function just like normal

**Comment by kumarharsh** [comment]
yea, that's why I was searching for some other solution when I saw your issue

**Comment by philipwalton** [comment]
I'm not sure I'm seeing how this works. I tried adding `height: 0` to both examples in the README, and neither of them fully works. The only one that works is the case where the content is shorter than the declared `min-height`.

Can you provide an example in case I'm missing what you're saying?

**Comment by philipwalton** [comment]
I'm going to close this as there's been no response to my question and I can't reproduce this myself. Feel free to reopen if you have more information.

**Comment by dan-gamble** [comment]
Sorry! Didn't see this, i can't remember the situation i needed this for as well. If i come across it again i will do :)

**Comment by kumarharsh** [comment]
I've found a very bad side-effect of using this approach: It makes the whole div get cut-off on the top when the window size is smaller than the content. In-short: Don't use it unless you're **absolutely** sure that your content won't ever get cut-off by height of the window
