### ISSUE TITLE
flex-grow: 0.001 produce inconsistant behavior with flex-wrap

### ISSUE THREAD

**Issue by slorber** [philipwalton/flexbugs#140]
The bug can be demonstrated by playing with window size in this JsFiddle: [https://jsfiddle.net/hbdLacz8/](https://jsfiddle.net/hbdLacz8/)

You can notice that according to the browser you use, when the 2 boxes go under 2 lines they do not behave the same.

On my recent chrome version the green box always takes the whole width (it grows), while on Firefox (44.0.2) it does not grow.

It seems I only get this behavior when using flex-wrap, because if I remove the red box from dom, the green box grows normally.

It was also reported on my Android phone (Chrome) and on a teammate desktop Chrome, so not sure it's only related to a specific browser.

Also note that if I use int values for flex-grow, then I get my expected behavior (by simply multipliying all the flex-grow by 1000. [See](https://jsfiddle.net/zmsqtc9c/)

I don't know what is supposed to be the standard behavior but I know browsers should rather behave the same...

**Comment by philipwalton** [comment]
Hmmm, personally, I've never seen much value in non-integer flex grow/shrink amounts. And if values less than one cause problems, maybe it's worth recommending that people always use positive values to avoid these inconsistencies.

Have you reported this to any browser vendors?

**Comment by slorber** [comment]
Yes there's not much value. I'm just reporting the problem.

I don't know which browser is right here anyway so I did not open any issue anywhere. What do you think is the correct behavior and to which browsers should I report?

**Comment by philipwalton** [comment]
Whenever I'm not sure which implementation is following the spec correctly (or whether any of them are), I usually email the [www-style](https://lists.w3.org/Archives/Public/www-style/) W3C list and pose the question.

If you mention that FF and Chrome are rendering this differently and you'd like to report the bug but you aren't sure who's correct, I bet you'll get an answer pretty quickly.

**Comment by tabatkins** [comment]
Chrome's fixed the issue more recently, it just hasn't percolated down to whatever version you're using.  This can be closed - it's a flexbug about to die.

(The correct behavior, that Firefox and newer Chrome implement, is that 'flex' is interpreted as a share of the free space that it wants.  If elements end up wanting more than 100%, they'll get scaled down appropriately, but they can ask for *less* than 100% too, and they'll get that.  This makes the behavior of 'flex-grow' animatable between 0 and >0, where previously (when they got scaled at all times, whether up or down) as soon as you had a >0 flex-grow it would take the entire space, so you couldn't animate something to/from 0.)

**Comment by slorber** [comment]
good to know :) thanks I'm closing this then

**Comment by kumarharsh** [comment]
@tabatkins great! can you tell which version of chrome, or which build/date-of-build would have fixed this? Would be good to know...

**Comment by tabatkins** [comment]
Not sure, unfortunately. Sometime between 48 and 50.

**Comment by kumarharsh** [comment]
ok. thanks :+1:

**Comment by MattyBalaam** [comment]
I think this is probably related to this https://github.com/philipwalton/flexbugs/issues/116

48-50 showed this issue, but it was fixed by version 51:

https://bugs.chromium.org/p/chromium/issues/detail?id=576202
