### ISSUE TITLE
inconsistent sizing across Chrome 49 and Safari 9.1 with flex-basis auto and 0%

### ISSUE THREAD

**Issue by kr** [philipwalton/flexbugs#142]
https://jsfiddle.net/0y8oqsne/1/

I dearly hope Chrome's behavior is correct, and that this is a Safari bug.

In Chrome 49:

<img width="714" alt="screen shot 2016-03-27 at 03 18 32" src="https://cloud.githubusercontent.com/assets/4178/14064944/9e710cd4-f3ca-11e5-9bd9-c1968d80eaf1.png">

In Safari 9.1:

<img width="735" alt="screen shot 2016-03-27 at 03 19 18" src="https://cloud.githubusercontent.com/assets/4178/14064951/c40b3b54-f3ca-11e5-96d6-3ad81f76fbf5.png">

**Comment by jpdevries** [comment]
Here's the same example in codepen http://codepen.io/jpdevries/pen/YqQYLz?editors=1100

Here it is forked with a few slight changes that seem to make it more compatible between Chrome and Safari.
http://codepen.io/jpdevries/pen/jqwYxG?editors=1100

I added `overflow-x:hidden` to `.right` to prevent the text from causing a horizontal scroll bar.

**Comment by philipwalton** [comment]
This is an example of Flexbug 1, and the min-content sizing of elements not being accounted for.

If you add the following CSS rule, Chrome renders the same as Safari:

```css
.title, .left, .right {
  min-width: 0;
}
```

Flexbug 1 has been fixed in Safari Tech Preview, and if you open your demo in that browser you'll see it's the same as Chrome.
