### ISSUE TITLE
The workaround of min-height in IE10 and IE11 not working

### ISSUE THREAD

**Issue by sidati** [philipwalton/flexbugs#147]
Hi,
in this workaround : http://codepen.io/philipwalton/pen/KwNvLo, if you give the site container a background-color and add more paragraph so the container height became greater than viewport height, if you try to scroll down you will see that the container is not taking all the height of content.

Any suggestions ??

**Comment by philipwalton** [comment]
If you apply the background color to the flex items instead of the container it should work.
