### ISSUE TITLE
Firefox will not honour flex properly on inputs

### ISSUE THREAD

**Issue by MattyBalaam** [philipwalton/flexbugs#152]
Input elements inside a flex-box decide they have an intrinsic size, which in some way is related to the font size.

To workaround, set a min-width of 0 on the input element.

http://codepen.io/MattyBalaam/pen/VaJjVq

https://bugzilla.mozilla.org/show_bug.cgi?id=1242914

**Comment by philipwalton** [comment]
I'm not sure this is a bug because I'm not sure the spec makes it explicit what the min-content size of an input is.

I'm going to close this because `min-width: 0` is probably what most people should use here anyway. It's not really a workaround, it's the recommendation.
