### ISSUE TITLE
Paragraph overflow when flex-direction row

### ISSUE THREAD

**Issue by AFerreli** [philipwalton/flexbugs#156]
Hi! In IE10 paragraph didn't wrap inside container with `flex-direction: wrap`.
Here is the discussion (StackOverflow) when i found the solution:
http://stackoverflow.com/a/33795089

For semplicity, add to the paragraph `flex-shrink: 1;` and the paragraph will wrap.

Can you add this case in the readme? Thanks in advance!

**Comment by philipwalton** [comment]
Thanks, but this is actually an example of Flexbug 6, and it's happening because by default IE10 sets `flex-shrink` to `0`.
