### ISSUE TITLE
When flexbox items wrap in column mode, container does not grow its width

### ISSUE THREAD

**Issue by Morkowski** [philipwalton/flexbugs#161]
http://stackoverflow.com/questions/33891709/when-flexbox-items-wrap-in-column-mode-container-does-not-grow-its-width

Example: http://jsfiddle.net/nwccdwLw/1/

**Comment by philipwalton** [comment]
Yeah, I reported this to Chrome some time ago:
https://bugs.chromium.org/p/chromium/issues/detail?id=507397

Unfortunately, I don't think there's a workaround.

**Comment by philipwalton** [comment]
I think this may also partially be related to Flexbug 14.
