### ISSUE TITLE
Setting height via padding on flex children

### ISSUE THREAD

**Issue by kthornbloom** [philipwalton/flexbugs#162]
Occasionally it's necessary for an item to have a height set proportionally to the width. You can do this by setting something like `padding-top:20%`. However, it seems only some browsers do it correctly when these elements are within a "flex" parent.

Demo for reference: https://jsfiddle.net/c4wmq19r/3/

**Comment by MadanBhandari** [comment]
yeah, it's not working for `padding-top:20%` but it's working for `padding-top:20px`

I have tested on Firefox.

**Comment by philipwalton** [comment]
I think this is a duplicate of #86, feel free to reopen if it's not.
