### ISSUE TITLE
Datepicker Trigger image doesn't scale when using flex

### ISSUE THREAD

**Issue by jdready5** [philipwalton/flexbugs#163]
When I am using flex the datepicker trigger image shrinks down to an unrecognizable image. I am using 3 elements. Has anyone else seen this behavior?

        flex: auto;
        flex: 1 1 20em;
        min-width: 33%;

**Comment by kumarharsh** [comment]
Are those styles applied on the same element? It doesn't make sense in that case.
Please post a reproducible example on jsfiddle

**Comment by philipwalton** [comment]
Closing as there's not enough information here to go off of.
