### ISSUE TITLE
Flex parent with height: auto and child with flex 1 not expanding in Safari

### ISSUE THREAD

**Issue by adamreisnz** [philipwalton/flexbugs#173]
A parent container with `height: auto` and `flex-direction: column` was not expanding properly in height when a child element had `flex: 1` applied and enough contents to fully expand in height.

Solution was to apply `flex-basis: auto;` to the child elements which. Only Safari was affected, it worked fine in Chrome.

**Comment by philipwalton** [comment]
Do you have a demo?

**Comment by adambuczynski** [comment]
It's pretty much this https://css-tricks.com/forums/topic/flexbox-item-not-expanding-to-full-height-of-parent-div-in-safari/

**Comment by philipwalton** [comment]
The demo you've linked is different from the description you gave. Please provide your own, simplified demo and specifically explain the problem and the workaround.

**Comment by adambuczynski** [comment]
http://codepen.io/anon/pen/VKvVmm

Left safari, right chrome:

![image](https://cloud.githubusercontent.com/assets/490562/18419671/7bdc3e4a-78b4-11e6-9102-8282d16cbbee.png)

Uncomment line 161 of the CSS to fix it for safari.

**Comment by VincentBel** [comment]
@adamreisnz @philipwalton I encountered the same problem. And I set up [a simpler demo](http://codepen.io/anon/pen/VKvVmm) to illustrate the problem.

![image](https://cloud.githubusercontent.com/assets/6076919/24396258/1badc068-13d5-11e7-8cf3-da36ca19fdd7.png)

I think the problem is caused by a **combination of `max-height` in parent and `flex: 1; overflow: auto;` in child**. Uncomment any one of the three can avoid the problem.

**Comment by mrahhal** [comment]
Also faced this. Removed `flex: 1` and it worked. @VincentBel's demo identifies the problem best.

Spent a lot of time on the main page of this repo and I almost missed this issue, so I think this should be added there.

**Comment by philipwalton** [comment]
For me to add this to the main repo README there needs to be browser bugs to go along with the workaround.

I'm going to close this in the interest of not having so many inactive, open issues. In anyone here is able to report or track down the relevant browser bugs and a clear solution is discovered, I'll add it to the README.

**Comment by wuz** [comment]
Worth mentioning this is the related bug in Safari: https://bugs.webkit.org/show_bug.cgi?id=137730

Hope that helps!

**Comment by pencilcheck** [comment]
"flex-basis 0px" wouldn't work in older version of IE that implements older spec of flexbox. Perhaps this is how safari was implementing flexbox as well.
