### ISSUE TITLE
bug stretches picture in ie11

### ISSUE THREAD

**Issue by webmarkelov** [philipwalton/flexbugs#174]
Hi, watch the following error: pulling unit with the image in ie11
http://codepen.io/webmarkelov/full/dpPqOa/

**Comment by webmarkelov** [comment]
lol) Resolve: for image max-width delete and set width: 100%

**Comment by philipwalton** [comment]
Do you have a workaround?

**Comment by webmarkelov** [comment]
No)), you can offer a solution?

**Comment by rtack** [comment]
considering that the codepen doesn't exist anymore, should this be closed?
