### ISSUE TITLE
IE11: single element vertical positioning via justify-content:  ist broken

### ISSUE THREAD

**Issue by dominiklenne** [philipwalton/flexbugs#175]
The container had 

```
flex-direction: column; 
justify-content: center;
```

The single element was positioned at the bottom.

`justify-content: flex-start;`

leads to positioning of the element in the center.

`justify-content: space-around;
`
gives the desired outcome.

**Comment by philipwalton** [comment]
Please post a demo showing the issue.

**Comment by dominiklenne** [comment]
[ie flex bug test.html.txt](https://github.com/philipwalton/flexbugs/files/507128/ie.flex.bug.test.html.txt)

**Comment by philipwalton** [comment]
You probably shouldn't be using `margin: auto` with either `align-items` or `justify-content` as they're different ways of doing the same thing.

**Comment by dominiklenne** [comment]
Hi Philip,

i admit that one could see this behaviour of IE both as a bug or no bug. 
I tend to the second because the other browsers get it right and IMO even if it is unnecessary specification, it should not result in neither of the specifications working, but at least one of them.
Double or even contradictory css styles should IMO result in one of the styles working.
But you are the boss here... 


Von: Philip Walton 
Datum: Dienstag, 18. Oktober 2016 01:48
An: philipwalton/flexbugs 
Cc: dominiklenne ; Author 
Betreff: Re: [philipwalton/flexbugs] IE11: single element vertical positioning via justify-content: ist broken (#175)

You probably shouldn't be using margin: auto with either align-items or justify-content as they're different ways of doing the same thing.

**Comment by philipwalton** [comment]
I agree it's a bug, I was just saying I don't think you should use both methods together.

In general I've only been adding to the main list bugs that a developers is likely to encounter while following best practices and for which a good workaround exists.
