### ISSUE TITLE
Safari flex-basis animation bug

### ISSUE THREAD

**Issue by DrummerHead** [philipwalton/flexbugs#176]
Test case at: https://github.com/DrummerHead/safari-flex-basis-animation-bug

Check with safari: http://mcdlr.com/safari-flex-basis-animation-bug/

Cheers!

**Comment by gregwhitworth** [comment]
@philipwalton do you have access to a machine with Safari on it?

**Comment by philipwalton** [comment]
I do, and I can confirm this doesn't work in Safari, even Safari 10. Here's a codepen to make it easier to see what's going on: http://codepen.io/anon/pen/rrqaQL

**Comment by DrummerHead** [comment]
Hi Philip! Just in case, (some) documentation is on the test case linked above; quick link:

https://github.com/DrummerHead/safari-flex-basis-animation-bug

**Comment by jeegurda** [comment]
Still not fixed in Safari 11 :/
The only workaround at the moment is to use `width`.

**Comment by dotnetCarpenter** [comment]
Damn - just found https://codepen.io/thomas-eilermann/pen/grjEjE, implemented it in my project and then began testing in all the browsers we support and bam, Safari 11 fail.

**Comment by dotnetCarpenter** [comment]
Couldn't find a bug report in webkit so I filed one: https://bugs.webkit.org/show_bug.cgi?id=180435

**Comment by dotnetCarpenter** [comment]
Fixed in Safari but still not released. A cautious 🎉 from me
