### ISSUE TITLE
Firefox: space-between doesn't ignore absolute-positioned elements

### ISSUE THREAD

**Issue by mrflix** [philipwalton/flexbugs#18]
Tested in Firefox 35.0.1.
Bug on bugzilla with testcase: https://bugzilla.mozilla.org/show_bug.cgi?id=865920

**Comment by safareli** [comment]
I also had this issue :/

**Comment by philipwalton** [comment]
I'm going to close this bug because it's old, and I don't know of a workaround. If someone wants to suggest one I'll reopen.

**Comment by mrflix** [comment]
Allright
