### ISSUE TITLE
`min-height` on a flex-container: unit can't be %

### ISSUE THREAD

**Issue by callumflack** [philipwalton/flexbugs#181]
To show how this breaks on current Safari (v10), I forked @philipwalton 's [3.2.a](http://codepen.io/philipwalton/pen/VYmbmj): http://codepen.io/callumflack/pen/bwvLYm

**Comment by philipwalton** [comment]
This works fine for me, the problem in your example is `<body>` doesn't have a definite height, so % on a child won't work. This is unrelated to flexbox, it's just part of how height works in CSS.

**Comment by callumflack** [comment]
Gotcha, my bad. Thanks.


Cheers, Callum
— — — — — —
I plan, design and build great user experiences from Cairns, Australia.
To learn more, visit patternworks.com.au <http://www.patternworks.com.au/>
Talk to me: 0408 767 540
