### ISSUE TITLE
Set flex-basis as % in safari not work!

### ISSUE THREAD

**Issue by EYHN** [philipwalton/flexbugs#195]
--> [https://jsfiddle.net/b85Lh1q2/29/](https://jsfiddle.net/b85Lh1q2/29/) <--

![20170125_210417-collage](https://cloud.githubusercontent.com/assets/13579374/22291550/ef004a5e-e341-11e6-9e8b-56b62db9ed87.jpg)

Above is chrome and below is Safari.

Can anyone tell me the solution?

**Comment by philipwalton** [comment]
This is due to min-content sizing as described in [flexbug 1].(https://github.com/philipwalton/flexbugs#1-minimum-content-sizing-of-flex-items-not-honored)
