### ISSUE TITLE
Clarify that the IE10-11 bugs are confirmed fixed in IE12

### ISSUE THREAD

**Issue by cvrebert** [philipwalton/flexbugs#2]
Bugs (2), (4), and (5), which affect IE11, don't have "Tracking bugs" columns.
Also might want to loop in the super-awesome @jonathansampson of the IE Team.
Anyway, cheers from a [fellow bug documenter](https://github.com/cvrebert/bs-css-hacks)!

**Comment by gregwhitworth** [comment]
Hey @cvrebert they are already fixed in IE12. @philipwalton just want to get work-arounds in the community so people don't have to try and track these down. That said, we may want to add that these have been fixed in IE12 so people don't think that the IE team is slacking on flexbox fixes.

**Comment by gregwhitworth** [comment]
@cvrebert I apologize for not introducing myself earlier; but I work on the layout team on Internet Explorer (I completely agree with your assessment of @jonathansampson as he is indeed super-awesome)!

**Comment by cvrebert** [comment]
Ah, I see. What with IE12 not being out yet (and there not being any bug links or clarifying notes), it's ambiguous whether 11 in an IE version range implies "and probably future versions, as far as we know" or not.
Yeah, just needs some "fixed in IE12" notes.
