### ISSUE TITLE
Flexbox scroll div in iOs Safari. Nothing.

### ISSUE THREAD

**Issue by johnunclesam** [philipwalton/flexbugs#215]
I don't know if this problem is already know.

http://stackoverflow.com/questions/43175481/different-behavior-of-flexbox-with-overflow-y-scroll-on-safari-firefox-and-ed

**Comment by philipwalton** [comment]
This issue report does not contain enough information to act on. Please update it with all the information in the [issue reporting guidelines](https://github.com/philipwalton/flexbugs/blob/master/.github/ISSUE_TEMPLATE.md) or close it if it's no longer relevant.
