### ISSUE TITLE
display:flex container expand horizontally with its wrapped contents

### ISSUE THREAD

**Issue by jogibear9988** [philipwalton/flexbugs#232]
Is this bug already reported ? (https://stackoverflow.com/questions/23408539/how-can-i-make-a-displayflex-container-expand-horizontally-with-its-wrapped-con)

There is also a workaround in the ticket!

**Comment by philipwalton** [comment]
Yep, this is already [flexbug 14](https://github.com/philipwalton/flexbugs#flexbug-14), but I updated the workaround to use that strategy, thanks!
