### ISSUE TITLE
Safari: Children with height and overflow hidden break parent height

### ISSUE THREAD

**Issue by cburgmer** [philipwalton/flexbugs#234]
A parent with two children, one with a percentage `height` value, one with `overflow: hidden set`, will yield an incorrect height in Safari 10.1.2.

Example: https://jsfiddle.net/cburgmer/mrzt7wjz/5/

IE11, Chrome and Firefox all agree on the rendering, and will show the second child. Safari will not show the text.

Happy for clarification, so I can raise an issue with Safari. Also still looking for a workaround.

**Comment by cburgmer** [comment]
Might be the same bug as reported in #198.

**Comment by philipwalton** [comment]
Closing as there's no workaround or bug report to link to, and it seems like this has been fixed in Safari 11. Feel free to open up a new issue if you discover a workaround.
