### ISSUE TITLE
Safari: align-items/justify-content ignored when flex container is button element

### ISSUE THREAD

**Issue by OliverJAsh** [philipwalton/flexbugs#236]
Not the same as https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers

### Things to include in your issue:

- Please include links to the bugs for each affected browser's bug tracker.

https://bugs.webkit.org/show_bug.cgi?id=169700

- Please include a live demo ([CodePen](https://codepen.io/) or [JSBin](https://jsbin.com)) showing both the issue and the workaround.

Issue:
- http://jsbin.com/dakutob/1/edit?html,css,output
  ![image](https://user-images.githubusercontent.com/921609/33606380-31afcaea-d9b5-11e7-890d-6c8331c85684.png)

Workaround:
- Wrap button contents in another flex container
  http://jsbin.com/dakutob/2/edit?html,css,output

- Please clearly explain exactly what the expected behavior is and what's not happening in the affected browser(s). It's not always immediately obvious from looking at a demo what is wrong.

The align-items and justify-content properties seems to be completely ignored when the flex container is a button.

**Comment by philipwalton** [comment]
Hmmm, is this fixed in Safari 11?

Since this is so similar to Flexbug 9 (the workarounds are exactly the same), if we determine this is still an issue I think it would make more sense to just add more detail to that bug and explain that the workaround is still recommended.

What do you think?

**Comment by neo** [comment]
Not anymore in 11, but still happens in 10, which is still quite popular?

**Comment by neo** [comment]
@OliverJAsh agreed that it's still worth documenting.

**Comment by philipwalton** [comment]
Since it's been fixed in Safari 11 and the README states this, I think it's OK to close this issue. Users who read the table can easily infer that the workaround is still necessary if they want to support Safari 10.

**Comment by OliverJAsh** [comment]
I raised a PR to reference the fixed Safari issue: https://github.com/philipwalton/flexbugs/pull/245

This extra detail might be useful for older Safari users, considering the bug is not the same as the other linked Safari issue.

**Comment by philipwalton** [comment]
Thanks, merged!

**Comment by cyan33** [comment]
Got the same issue in safari 10. Thanks for the workaround! @OliverJAsh  👍

**Comment by PradnyaSahajrao** [comment]
how to make flex and align-items works for IPAD air 4
