### ISSUE TITLE
Can't reproduce flexbug 4 in IE 11 any more

### ISSUE THREAD

**Issue by simonbuchan** [philipwalton/flexbugs#249]
Description claims that `flex: 1 0 0` will be ignored by IE 11, but from what I can tell, this is no longer the case:

![image](https://user-images.githubusercontent.com/1840547/35704072-164053a2-0803-11e8-8c7d-3a49f78f5aef.png)

The output is the same as the workaround and chrome. I don't know why this would have changed since IE 11 release though?

**Comment by mgol** [comment]
I still see the bug in IE 11 on Windows 10 with all updates installed. IE reports its version as `11.371.16299.0`.

<img width="993" alt="screen shot 2018-04-17 at 23 40 46" src="https://user-images.githubusercontent.com/1758366/38899632-cb979614-4298-11e8-951c-0e7db12976a3.png">

**Comment by simonbuchan** [comment]
No idea, I also can't (not) reproduce it now.
Chalking this up to either a codepen failure to refresh or some weird patch version of IE that fixed it then reverted it.
Or I'm so crazy my screenshots are crazy!
