### ISSUE TITLE
The codepens for 12.1a and 12.1b have the same code

### ISSUE THREAD

**Issue by sipec** [philipwalton/flexbugs#281]
Currently the codepens for 12.1a and 12.1b both have the same code. IMO the examples ought to be on git instead of in codepen, so that errors like this can be referenced correctly

**Comment by akaustav** [comment]
@philipwalton Feel free to correct me and/or add more information which I might have missed.

Hi @sipec, thanks for bringing this to our attention. First of all, I can't seem to reproduce [12.1.a](https://codepen.io/philipwalton/pen/qdMgdg) bug in the version of IE11 installed on my Windows 10 machine (version screenshot below) - and I do not have access to older versions of IE.

![image](https://user-images.githubusercontent.com/11030959/76092508-bd9d2f80-5f7c-11ea-94e9-1e41d1f3cccf.png)

However, I verified that there is indeed a difference in the CSS on both examples. In the [12.1.b](https://codepen.io/philipwalton/pen/NqLoNp) workaround, I noticed this extra piece of CSS rule:

```css
.FlexContainer::before,
.FlexItem {
  display: block;
}
```

There is an ongoing effort to move these examples from Codepen into GitHub for a different reason - see issue #274 and PR #276.

**Comment by akaustav** [comment]
@philipwalton Feel free to correct me and/or add more information which I might have missed above.

On a related note, I can't seem to find any difference in the outputs between the [12.1.a](https://codepen.io/philipwalton/pen/qdMgdg) bug and [12.1.b](https://codepen.io/philipwalton/pen/NqLoNp) workaround in the version of IE11 installed on my Windows 10 machine (11.657.18362.0 - version screenshot below). And I do NOT have access to older versions of IE.

I was expecting to see a difference between the `::before` element as per the following statement mentioned on the description of this bug.

> IE 11 fixed this bug with regular inline element, but it still affects the ::before and ::after pseudo-elements.

Looks like the latest patch of IE11 might have fixed the issue on the `::before` and `::after` pseudo-elements.

## My IE11 Version
![image](https://user-images.githubusercontent.com/11030959/76092508-bd9d2f80-5f7c-11ea-94e9-1e41d1f3cccf.png)


## Output of [12.1.a](https://codepen.io/philipwalton/pen/qdMgdg) bug
![image](https://user-images.githubusercontent.com/11030959/76094654-35b92480-5f80-11ea-861e-6704a7d6aa40.png)


## Output of [12.1.b](https://codepen.io/philipwalton/pen/NqLoNp) workaround
![image](https://user-images.githubusercontent.com/11030959/76094707-4c5f7b80-5f80-11ea-8bf7-d17c1be16317.png)

**Comment by sipec** [comment]
My bad, I the difference now. I just didn't scroll down :sweat_smile:
