### ISSUE TITLE
Problem with animated sprites in flexbox

### ISSUE THREAD

**Issue by BlackMagic** [philipwalton/flexbugs#29]
I'm developing a website using flexbox and want to use animated sprites on it. Flexbox doesn't like animated sprites and they throw flexbox's calculations out dramatically. There are two websites where the code is demonstrated: ieee-qld.org/flex-bad and ieee-qld.org/flex-good. On the first site the animated graphic is 75% bigger than it should be, spreading over two sprite frames. 

In the code below I've commented out the flexbox-enabling code (ieee-qld.org/flex-good). Removing the comments causes the animated sprite to misbehave (ieee-qld.org/flex-bad).

    <!doctype html>
    <html>
    <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>flex problem</title>
    </head>
    <body>
    <style>
    * {margin:0; padding:0; border:0; outline:0; vertical-align:baseline; background:transparent;}
    body {line-height:1.5; font-size:75%; color:#222; background:#b6d3e4; font-family:"Helvetica Neue", Arial, Helvetica, sans-serif;}
    .sprite {width:150px; height:130px; border-width: 5px; border-style:solid; border-color:#ffffff; border-radius:5px; background-image:url("sprite.jpg");
        -webkit-animation: play 20s steps(4) infinite;
        -ms-animation: play 20s steps(4) infinite;
        animation: play 20s steps(4) infinite;}
    @-webkit-keyframes play{from{background-position:0px;}to{background-position:-600px;}}
    @-ms-keyframes play{from{background-position:0px;}to{background-position:-600px;}}
    @keyframes play{from{background-position:0px;}to{background-position:-600px;}}

    header {background:#4971a2; position:fixed; left:0px; top:18px; height:15%; width:100%; clear:both;}

    /* ************** flexbox code commented out at ieee-qld.org/flex-good *************************
    .box {flex:1;}
    .box:nth-child(2){flex-grow:2;}
    .flexy {display:flex;flex-direction:row;align-items:center;height:30px;background:yellow;}
    * {-webkit-box-sizing:border-box; -moz-box-sizing:border-box; box-sizing:border-box;}
    ***************************************************** */
    .c {text-align:center;}
    .bold {font-weight:bold;}
    .box {margin-left:4%; margin-right:4%;}
    h1,h2,h3,h4,h5,h6 {font-weight:normal; color:#111;}
    h1 {font-size:3em; line-height:1; margin-bottom:0.5em;}
    </style>
      <header>
      <div class="flexy">
        <div class="box sprite"></div>
         <div class="box"><h1 class="c bold">IEEE Queensland Section</h1></div>
        <div class="box">clue</div>
      </div>
      </header>
     </body>
    </html>

The sprite is attached below.
![](https://cloud.githubusercontent.com/assets/333647/6866566/4fdaa172-d4c5-11e4-88ef-f9175a029b09.jpg)

**Comment by BlackMagic** [comment]
![sprite](https://cloud.githubusercontent.com/assets/333647/6866566/4fdaa172-d4c5-11e4-88ef-f9175a029b09.jpg)

Sorry, I attached the wrong version of the sprite earlier.

I have tested this error on Windows 7 using the latest versions of IE11, Chrome, Opera and Firefox. All browsers give the same error.

Today I tested it on a friend's Mac running Safari and the problem didn't occur. When we switched to Chrome on the Mac the problem the problem appeared.

**Comment by gregwhitworth** [comment]
I haven't had a chance to dig into this issue yet, but I did have time before work to place your code and sprite into jsbin for everyone to easily mess around with.

http://jsbin.com/xudimajewu/1/edit

**Comment by gregwhitworth** [comment]
And here is one with the commented code in place
http://jsbin.com/vamiqezulo/1/edit

**Comment by gregwhitworth** [comment]
I now really, have to get to work - but if anyone takes a look at this - it can't be the animations themselves as removing them (http://jsbin.com/notazezeru/1/edit) causes no issue. So it is indeed the commented code is just causing a nested flex issue that we need to reduce @BlackMagic if you have the time, if you could reduce this code by removing the non-necessary code from the jsbin in this comment it will make it easier for us to find the issue. Thanks.

**Comment by BlackMagic** [comment]
@gregwhitworth The only code I could take out is code that refers to <section> and <footer>, ie 6 lines in HTML and 2 lines in CSS. 

The flexbox is nested in <header> and the sprite is nested in the flexbox. The CSS sprite animation code starts with ".sprite  {width:150px;..." and ends with "@keyframes play...", ie 4 lines of CSS.

All of the jsbin examples show the sprite frames properly rendered so I'm not sure if that is any help. The problem is that flexbox is rendering the sprite frames incorrectly in browsers, as can be seen at ieee-qld.org/flex-bad.  ieee-qld.org/flex-good has no flexbox code in it. 

Hope this helps.

**Comment by BlackMagic** [comment]
I've updated the code and cloned it here http://jsbin.com/vadayu/1/edit?html,css,output

**Comment by gregwhitworth** [comment]
Alrighty, sorry for the delay. I finally found time to look into this. The problem ultimately was setting a height on .flexy. I have this working in Chrome/FF/IE11+ and changed .flexy to use a background gradient to achieve your yellow stripe over the blue. You'll need to tweak it to your liking. I added the animations back in and it is working as expected. I noticed on your live examples that the content was going vertically but kept the flex-direction that you set at row, you can easily change this by setting it to column, and adjusting the items locations. Additionally, I worked around some sizing issues by telling the sprite that it has to be 150px in size as FF/Chrome/IE were all sizing it differently due to interop issues. Let me know if you have any other questions. Closing this.

http://jsbin.com/kigaxozabo/2/edit

**Comment by BlackMagic** [comment]
@gregwhitworth Thanks. I'll check the solution out later when I have time to fiddle with it. I'll let you know if there are any side-effects.

The yellow stripe is unimportant. I put it there to visually differentiate flex-bad from flex-good.

**Comment by BlackMagic** [comment]
Could you reopen this issue please? The code below better reflects the way I want to use animated sprites. The sprite is taking up the entire width of the flex item instead of confining itself to the first 140 pixels. The error appears on Chrome, FF, Opera and IE11.

    <!doctype html>
    <html>
    <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>flex problem</title>
    </head>
    <body>
    <style>
    * {margin:0; padding:0; border:0; outline:0; vertical-align:baseline;}
    body {line-height:1.5; font-size:75%; color:#222; background:#b6d3e4; font-family:"Helvetica Neue", Arial, Helvetica, sans-serif;}
     .sprite {width:150px; height:140px; border-width: 5px; border-style:solid; border-color:#ffffff; border-radius:5px; background-image:url("sprite.jpg");
      -webkit-animation: play 30s steps(6) infinite;
      animation: play 30s steps(6) infinite;}
    @-webkit-keyframes play{from{background-position:0px;}to{background-position:-900px;}}
    @keyframes play{from{background-position:0px;}to{background-position:-900px;}}

    header {display:flex;flex-direction:row;align-items:center; background:#4971a2; position:fixed; left:0px; top:18px; height:25%; width:100%;}
    .box {flex:1;}
    .box:nth-child(2){flex-grow:2;}
    .c {text-align:center;}
    .bold {font-weight:bold;}
    h1,h2,h3,h4,h5,h6 {font-weight:normal; color:#111;}
    h1 {font-size:3em; line-height:1; margin-bottom:0.5em;}
    </style>

    <header>
         <div class="box sprite"></div>
         <div class="box"><h1 class="c bold">IEEE Queensland Section</h1></div>
         <div class="box">Logos</div>
    </header>
    </body>
    
![sprite](https://cloud.githubusercontent.com/assets/333647/7195682/0ecefc3a-e507-11e4-8a41-59636255e404.jpg)
</html>

**Comment by BlackMagic** [comment]
Could you reopen this issue please?

**Comment by BlackMagic** [comment]
Hi Folks,

Could you give me an outline of the logistics for this coming weekend 
please?

Saturday is an important day for an important person in my life.

Mike shushu
