### ISSUE TITLE
Seems like IE ignores calc in more instances than shorthand

### ISSUE THREAD

**Issue by corysimmons** [philipwalton/flexbugs#32]
https://github.com/philipwalton/flexbugs#8-flex-shorthand-doesnt-support-calc

See my comment here: https://github.com/closingtag/calc-polyfill/issues/9#issuecomment-89614643

**Comment by gregwhitworth** [comment]
Hey Cory, can you be more specific in regards to which IE version you're testing as I'm not seeing this behavior in IE11.
![calc-longhands-test](https://cloud.githubusercontent.com/assets/865244/6994359/72d16916-dacb-11e4-85fe-59a299456f17.PNG)

**Comment by gregwhitworth** [comment]
Oh, and here's the JSBin with your testcase: http://jsbin.com/keziveguna/1/edit?output

**Comment by corysimmons** [comment]
![](http://i.imgur.com/3NAc9YL.png)

Same JSBin doesn't work in IE10. I don't have IE11 (pretty big VM), but yeah, `flex-basis` doesn't seem to work in IE10. :(

**Comment by mestaritonttu** [comment]
![win8_ie_10 0](https://cloud.githubusercontent.com/assets/829167/6995844/d0914f2c-db6a-11e4-8bc3-3603347d9e73.png)
Screenshot from Browserstack IE10.

IE11 works ok, checked locally in Win 7.

**Comment by corysimmons** [comment]
If anyone of decent JS skill is interested in working on the calc polyfill for this, I'd really appreciate it: https://github.com/closingtag/calc-polyfill/issues/9

Without IE10 support for calc in Flexbox, I can't build one of my grids in it... =[

**Comment by flip4bytes** [comment]
+1 if anyone can get achieve this it'd be absolutely killer!

**Comment by philipwalton** [comment]
Weird. I don't know how I missed this not working in IE10, but it looks like you're right.

An easy workaround, though, assuming you know whether you're in a row or column flex container, is to use `flex-basis: auto` and then set your calc property on the width, for example:

```css
flex: 0 0 auto;
width: calc(100%/3);
```

This works for me in IE10.

**Comment by corysimmons** [comment]
But if you're using `width` what's the point of using Flexbox?

**Comment by flip4bytes** [comment]
I definitely agree with you @corysimmons though isn't the main point of flexbox that it eliminates the need for floats? It does seem really stupid though that the fix for IE10 is to set a width though. Sounds really counter-productive.

**Comment by corysimmons** [comment]
I'm not convinced getting rid of clearfixes/floats is a good enough reason to drop browser support for IE8-9.

**Comment by flip4bytes** [comment]
Very true, which maybe that just means flexbox truly isn't ready yet then? Once IE8 and IE9 finally vanish (IE8 is getting there, even though in theory it's already on EOL, but some XP users are still using it of course). Then maybe that's when flexbox finally makes some sense and it's worth getting rid of floats at that point?

**Comment by philipwalton** [comment]
> But if you're using width what's the point of using Flexbox?

Tons of reasons: equal height flex items, vertical centering, proper baseline alignment, the flex properties (they still work even with a definite flex-basis), and many more.

**Comment by corysimmons** [comment]
@philipwalton Fair enough. I'll tinker around with this tonight and see if it solves any of my problems.

**Comment by corysimmons** [comment]
@philipwalton Seems to work pretty well. https://github.com/corysimmons/lost

**Comment by philipwalton** [comment]
Closed via 1e0e0f55c3a0292d00012f649a31618ededdd76a.
