### ISSUE TITLE
Safari max-width issue on children in flex container

### ISSUE THREAD

**Issue by TPDBrendan** [philipwalton/flexbugs#33]
Just noticed an odd bug that I'm only seeing in Safari right now.  When children of a parent container set to flex are given a fluid width and a static max-width, the max-width doesn't seem to override.  

My solution for now is to just set the parent to text-align:center and the children to display:inline-block, but it seems odd that this works in Chrome, Safari and IE.

**Comment by philipwalton** [comment]
Can you link to an example? What you describe works fine for me in Safari:
http://codepen.io/anon/pen/NPZRXV

**Comment by TPDBrendan** [comment]
Sure thing.  Updated Codepen here: http://codepen.io/TPDBrendan/pen/NPZRzQ

Tested with Safari 7.1.5.

**Comment by philipwalton** [comment]
That's working exactly as expected for me, both on Safari 7 and 8.

**Comment by TPDBrendan** [comment]
Hmm, that's odd.  This is what it looks like for me in Chrome and Safari, respectively.

![chrome](https://cloud.githubusercontent.com/assets/7327485/7073763/ba6d4dc0-dec3-11e4-9b6c-eb90435f9f05.png)
![safari](https://cloud.githubusercontent.com/assets/7327485/7073768/c0f306f8-dec3-11e4-88f3-a795a65990ba.png)

**Comment by philipwalton** [comment]
Ahh, I see what you're talking about now. My window was at the perfect size where they were both wrapping the same way.

It looks like this only affects multi-line flex containers. Safari is using the `max-width` declaration to size the element, but it's using the `width` declaration to determine wrapping.

**Comment by wasd171** [comment]
Has anyone found a workaround excluding media queries? I'm trying to create layout which automatically switches from 2 to 3 columns, but it seems broken in Safari, the blocks just overflow the screen. Everything works perfectly in Chrome :-( http://codepen.io/anon/pen/jPPJGO

**Comment by JeanRemiDelteil** [comment]
It's the same things for fixed min-width and width in percent:
http://codepen.io/anon/pen/KpoQew
It overflows and always calculate wrapping using width in percent.
Using "justify-content: center" makes things way worst by clipping the left overflow.

Incorrect on
- IOS (safari / chrome) and safari on MacOS.
- Android 4.4.2 browser (blink v534.24)

Correct on Chrome for MacOs and every other browser I tested  (windows, android)

**Comment by philipwalton** [comment]
I added [flexbug 12](https://github.com/philipwalton/flexbugs#12-min-and-max-size-declarations-are-ignored-when-wrapping-flex-items) to address this issue via 45e93271990b085b961f93b5d1e02ba5f27bcc49.

**Comment by simonsmith** [comment]
I think I'm experiencing something similar, however when images are added into the mix IE10 and 11 are affected. 

Expected:
<img width="1011" alt="screen shot 2015-11-02 at 22 15 07" src="https://cloud.githubusercontent.com/assets/360703/10896014/36952024-81af-11e5-96c3-c8e4b1034516.png">

Safari:
<img width="346" alt="screen shot 2015-11-02 at 22 15 46" src="https://cloud.githubusercontent.com/assets/360703/10896030/4ce1f078-81af-11e5-81ad-88ad0dd79f01.png">

IE10:
<img width="751" alt="screen shot 2015-11-02 at 22 17 02" src="https://cloud.githubusercontent.com/assets/360703/10896062/7b51ffca-81af-11e5-9597-6838ddc01965.png">

Here is a pen - http://codepen.io/simonsmith/pen/WQKpaa?editors=110

In my scenario just setting the `width` to match the `max-width` solves it, but that probably won't fix every use case

**Comment by philipwalton** [comment]
It's been a while since I've looked at this bug, but it seems like not having a `width` or a `flex-basis` is the source of the problem.

You've written:

```css
.FlexItem {
  flex: 1 0 auto;
  max-width: 33.33333%;
}

but isn't that exactly the same as this?

```css
.FlexItem {
  flex: 0 0 33.333%;
}
```

Setting the `flex-grow` portion to `0` is effectively a `max-width`.

**Comment by simonsmith** [comment]
Yeah, it stems from trying to avoid the box-sizing issue in 7 https://github.com/philipwalton/flexbugs/blob/master/README.md#7-flex-basis-doesnt-account-for-box-sizingborder-box

I could try the second workaround there instead though
