### ISSUE TITLE
Weird positioning when adjacent overlapping div contains float

### ISSUE THREAD

**Issue by nanaya1** [philipwalton/flexbugs#34]
Demo: http://codepen.io/anon/pen/ogrYOr

I expected the flex container div to be sized and positioned according to its parent (just like block) div but it's not.

- ie/chrome: instead of top of parent div, it's positioned right below float of adjacent parent div (sorry I don't know how to properly say it)
- firefox: just weird

Am I missing something?

**Comment by nanaya1** [comment]
I noticed setting `overflow: hidden` on `.parent` makes the flex container behave as I'd expect.

**Comment by philipwalton** [comment]
According to the [spec](http://dev.w3.org/csswg/css-flexbox/#flex-containers):

> floats do not intrude into the flex container

This would explain why the flex container is being rendered directly below the floated items (in Chrome). 

As for which behavior is correct (Chrome/IE vs. FF), I'm not sure, but I don't think it has anything to do with Flexbox. If you remove the `.child` element (the only thing with `display: flex`), there is still a rendering difference, and I think that's the heart of the problem.
