### ISSUE TITLE
Safari Flex-Wrap on overflow: auto removes scrollbars

### ISSUE THREAD

**Issue by compton-blake** [philipwalton/flexbugs#36]
## Safari removes scrollbars when using flex-wrap

[CodePen Example](http://codepen.io/anon/pen/gbVyxo)

If you look at the `.row{}` selector in the CSS you will see that the `-webkit-flex-wrap: wrap;` property is set.

In Safari, removing that line of code makes the scrollbars reappear.

**Comment by philipwalton** [comment]
Can you try reducing this a bit more? My example here works just fine in Safari, so it doesn't affect all instances of `flex-wrap`.
http://codepen.io/anon/pen/gbVyxo?editors=110

**Comment by compton-blake** [comment]
Hmmmm... I checked out the link you provided (in Safari) and it is still giving me the same result. No scrolling content. Maybe it is my version specifically? I am using : Version 8.0.5 (10600.5.17).

Here is a gif showing no sidebars: http://g.recordit.co/ErwzSOkRPA.gif

**Comment by philipwalton** [comment]
Hmmm, looks like I accidentally linked to the wrong version. Either way, I was able to reproduce it more, and in this [codepen](http://codepen.io/anon/pen/eNgENP) you can see the bug in Safari. Commenting out the `flex-wrap` line makes it work correctly.

**Comment by philipwalton** [comment]
I'm not really sure if this is problematic enough to be listed in this repo though. In your example, you've used flex wrap in a situation where you don't actually want wrapping, so I think the solution would be pretty obvious to most developers.

I do think it should be reported to Safari. If you do that, can you paste the bug link here so others who find this issue can follow it?

**Comment by compton-blake** [comment]
Oh yeah, in this example it makes zero sense. I didn't want to code out the whole example with wrapped boxes. In the real world application of `flex-wrap` I had multiple boxes all using wrap to "float (for lack of a better term)" the boxes next to each other and wrap down the page. In that real world example this small line of code breaks the layout and created a big headache for me because I wouldn't have thought flex-wrap would give that result. Anyways, thanks for your time to look into this issue and I appreciate it.
