### ISSUE TITLE
Firefox: baseline alignment doesn't work with nested flex blocks

### ISSUE THREAD

**Issue by wilddeer** [philipwalton/flexbugs#40]
**Bug:** `align-items: baseline` doesn't properly align flex items of nested blocks with `display: flex`.

**Workaround:** Use `display: inline-flex` instead.

**Demo:** http://codepen.io/wilddeer/pen/aObevX

Tested in Firefox 37.0.1

**Comment by philipwalton** [comment]
Thanks, I noticed this too and [reported it](https://bugzilla.mozilla.org/show_bug.cgi?id=1146442) on Bugzilla about a month ago. The bug was accepted so quickly I thought perhaps it'd be fixed quickly too, so I didn't take the time to make a Flexbug for it.

It looks like I probably should though.

**Comment by philipwalton** [comment]
Added via d65774781950e211a1831c29b071b0eb343ca3e8.
