### ISSUE TITLE
centered image may lost a part

### ISSUE THREAD

**Issue by jiyinyiyong** [philipwalton/flexbugs#43]
Explained in this question:
http://stackoverflow.com/questions/24538100/issue-when-centering-vertically-with-flexbox-when-heights-are-unknown

![](http://i.stack.imgur.com/Jx15X.jpg)

But I'm not sure if that's a *true* bug or a tricky part of Flexbox?

**Comment by philipwalton** [comment]
I don't think this is a true bug as all browsers I loaded the codepen on behave the same way. If a different behavior is expected, a better place to ask/propose would be the www-style mailing list.
