### ISSUE TITLE
Flexbox doesnt work in fieldset

### ISSUE THREAD

**Issue by Krekotun** [philipwalton/flexbugs#44]
https://code.google.com/p/chromium/issues/detail?id=262679
http://stackoverflow.com/questions/19679337/why-are-not-all-flexbox-elements-behaving-like-flexbox-divs

**Comment by jpdevries** [comment]
This seems similar to [Flexbug 9](https://github.com/philipwalton/flexbugs#9-button-elements-cant-be-flex-containers) as it deals with certain tags not supporting flexbox

**Comment by LandonSchropp** [comment]
I've been able to reproduce this in Chrome, Safari and Firefox. It works correctly in IE10 and IE11. Here's a [test CodePen](http://codepen.io/LandonSchropp/pen/oXGMqY).

**Comment by CapitalH** [comment]
This would be a simple workaround for the fieldset issue:

```
<fieldset>
    <div>
        <p>First</p>
        <p>Second</p>
         <p>Third</p>
    </div>
</fieldset>
```

**Comment by philipwalton** [comment]
@gregwhitworth do you know if this is the intended behavior per the spec for `<fieldset>` elements? I'm happy to roll this into flexbug 9 and document the workaround, but I don't want to call it a bug if it's not.

I'm also curious if you know if there's a reason this "worked" in IE11 but is now "not working" in Edge.

**Comment by cvrebert** [comment]
`<fieldset>`'s rendering isn't adequately spec'd anywhere in general.
> "`<fieldset>` has magical rendering behavior."
> – [TabAtkins](http://krijnhoetmer.nl/irc-logs/whatwg/20150829#l-173)

**Comment by philipwalton** [comment]
I updated flexbug 9 to include fieldset in c8cb9f1a7c5695d0692d13fdb18dfe03f402c073.

**Comment by cvrebert** [comment]
@philipwalton Your `fieldset` reset snippet in those CodePens seems to be missing `min-width: 0;`, which is needed to reset [the default `min-width: min-content;` of `fieldset`s](https://html.spec.whatwg.org/multipage/rendering.html#the-fieldset-and-legend-elements)

**Comment by philipwalton** [comment]
@cvrebert Interesting, I didn't know user agent styles added `min-width: min-content` to `<fieldset>` elements. Though I wasn't really thinking of that rule as a reset. I just didn't want to make adding the `FlexContainer` class to the child `<div>` completely change the look.

In this case, I don't think adding `min-width: 0` makes any presentational difference, so it seems preferable to not add extra declarations that may just end up confusing people.
