### ISSUE TITLE
Chrome 43 flex shrinks element when overflowing sibling and absolute positioned parent

### ISSUE THREAD

**Issue by suhajdab** [philipwalton/flexbugs#47]
Anyone care to verify? I don't have any time for it.

https://twitter.com/suhajdab/status/601618268751822849

**Comment by janroudaut** [comment]
Confirmed on Chrome 43 (Windows 8.1).

Fixed by adding

```css
max-height: 100%;
height: 100%;
box-sizing: border-box;
```

to the `section` block.

http://codepen.io/janroudaut/pen/QbGJpd

**Comment by philipwalton** [comment]
This is an example of Flexbug 1, you can see for yourself because it's fixed in Chrome Canary.
