### ISSUE TITLE
Chrome does not size children correctly on basic flex

### ISSUE THREAD

**Issue by jakezatecky** [philipwalton/flexbugs#48]
I have a very basic example that contains a parent set to `display: flex` and two paragraph elements.

``` css
.flex {
    display: flex;
    width: 400px;
}
```

On Firefox and IE, these two paragraphs are appropriately sized and contained within the parent container. On Google Chrome, the first paragraph utilizes more space than necessary and makes the second paragraph overflow.

See the following simple [example](http://codepen.io/anon/pen/zGKJmB) that works on IE/Firefox, but not Chrome.

Any ideas how to workaround this?

**Comment by annamalai-saro** [comment]
Try adding 

.green
{
    background: #080;
    flex:1;
}

See this example [codepen] (http://codepen.io/anon/pen/MwbBEr)

**Comment by jakezatecky** [comment]
Great suggestion! That indeed works. Based on that solution, I also tried applying `flex-shrink: 0` to the `.yellow` flex item (see [example](http://codepen.io/anon/pen/vOyQPN)). So there appears to be at least a couple of ways to workaround this Chrome behavior.

**Comment by annamalai-saro** [comment]
@jakezatecky  Yea ..I agree there are multiple ways to solve this problem..great !

**Comment by philipwalton** [comment]
Yes, just use `flex-shrink:1`. This is an example of Flexbug 1.
