### ISSUE TITLE
justify-content: flex-end and overflow: auto don't play along

### ISSUE THREAD

**Issue by HugoGiraudel** [philipwalton/flexbugs#53]
Related tweet: https://twitter.com/HugoGiraudel/status/601740314282430464.
Relevant demo: http://codepen.io/HugoGiraudel/pen/EjgeaY/.

**Comment by philipwalton** [comment]
Did you have a workaround in mind for this?

**Comment by HugoGiraudel** [comment]
Nope. :(

**Comment by philipwalton** [comment]
No worries, I think it's good to have these sorts of bugs documented here in case others have the same issue, but I'm going to reserve the "official" list in the README for common issues with known workarounds.

Feel free to reopen if you have a workaround suggestion or get new information from FF.

**Comment by lyz452** [comment]
One year later... Any solution for this?

**Comment by philipwalton** [comment]
I think this proposed workaround might solve it, but I haven't had enough of a change to look into it yet:
https://github.com/philipwalton/flexbugs/issues/136#issuecomment-199641030

**Comment by lyz452** [comment]
If anyone needs a solution to this problem:
In my case instead of using "justify-content: flex-end", I did some trick by adding "direction: rtl" to the wrapper and then reversing it back to "ltr" inside the items

**Comment by patoezequiel** [comment]
I found a workaround for this. Use `justify-content: flex-start` (or whatever, really) and add a `**selector** > :first-child { margin-top: auto }` so it pushes the rest of the items to the bottom of the flex container.

**Comment by baig** [comment]
@patoezequiel Thank you! You saved me from wasting a lot of hours. This workaround still works.

**Comment by patoezequiel** [comment]
@baig you're welcome!

**Comment by P1X3L** [comment]
You could also reverse the order of the children before using `flex-direction: row-reverse`.
[This codepen](https://codepen.io/p1x3l-the-sans/pen/ZEbpvyx?editors=1111) shows how

**Comment by qalqi** [comment]
https://stackoverflow.com/questions/47372148/overflow-auto-not-working-with-justify-content-flex-end
