### ISSUE TITLE
Flexbox overflow bug (codepen)

### ISSUE THREAD

**Issue by andresbc** [philipwalton/flexbugs#54]
http://degradingdisgracefully.com/ie11-ie10-flexbox-overflow-bug/

**Comment by jpdevries** [comment]
I feel your pain.

Sounds like it could be related to this issue https://github.com/philipwalton/flexbugs/issues/51

Do you have an examples I could look at that reproduce the issue (your codepen works).

**Comment by philipwalton** [comment]
Your codepen has autoprefixer turned on, are you using autoprefixer on your site too?

**Comment by andresbc** [comment]
Hi,
The test case was written by someone else. Just wanted to share it with you because at the time it seemed different from the ones you had documented.

**Comment by philipwalton** [comment]
I'm not clear on what the bug is here. I'm going to close this issue, but feel free to reopen and elaborate if you think I'm missing something.
