### ISSUE TITLE
Chrome v44 flexbox height calculation change

### ISSUE THREAD

**Issue by slwfleming** [philipwalton/flexbugs#56]
Scroll bars created with overflow: auto disappeared in my web app when viewed in Chrome v44. They worked as designed in Chrome v43. 

The workaround turned out to be adding a max-height: 75vh; to the overflow container. Additionally a background color should be applied to the overflow container to prevent the content from expanding outside of the parent container's background-color. 

The fixed example uses some set height elements that needed to be further calculated. These examples show a slightly complex design.

Before the viewport height fix:
http://codepen.io/slwfleming/pen/aOWaqQ

Using the viewport height fix:
http://codepen.io/slwfleming/pen/VLbGvR

**Comment by philipwalton** [comment]
This is just another occurrence of flexbug 1. Also, in the future, please submit simplified demos. The more complex the demo, the harder it is to track down the root of the problem.
