### ISSUE TITLE
Chrome column flex overflow issue

### ISSUE THREAD

**Issue by bhoop** [philipwalton/flexbugs#60]
Chrome 43 is doing weird things when a flexed child has long content (i.e. a scrollbar) - Chrome is shrinking the height of the (non-flexing) siblings:

https://jsfiddle.net/10uc50ea/

![compare](https://cloud.githubusercontent.com/assets/2012803/8098486/cc78c392-0fbe-11e5-8e08-978fa629ff0b.jpg)

**Comment by jpdevries** [comment]
@bhoop try [this](http://codepen.io/jpdevries/pen/PqjmZW)
Notice the codepen has Autoprefixer enabled for vendor prefixing flexbox

```html
<header>Header</header>
<div id="stretch">
  <span id="space"></span>
</div>
<footer>Footer</footer>
```

```scss
header, footer {
  flex-shrink:0;
}
```

**Comment by bhoop** [comment]
That worked perfectly, thank you @jpdevries
