### ISSUE TITLE
Firefox min-height: 0; fix for overflow issue

### ISSUE THREAD

**Issue by andresbc** [philipwalton/flexbugs#65]
Here's another you may be interested in. I'm not sure if it as a bug or not but we just hit it:

http://stackoverflow.com/questions/28636832/firefox-overflow-y-not-working-with-nested-flexbox
https://bugzilla.mozilla.org/show_bug.cgi?id=1043520
http://stackoverflow.com/questions/26895349/how-can-i-get-ff-33-x-flexbox-behavior-in-ff-34-x

**Comment by philipwalton** [comment]
This is Flexbug 1 as it's related to the spec changes re: the new minimum default content sizing.
