### ISSUE TITLE
max-height with flex-direction columns and wrapping

### ISSUE THREAD

**Issue by lambert-velir** [philipwalton/flexbugs#66]
http://codepen.io/lambert-velir/pen/ZGrrNy

**Comment by jpdevries** [comment]
Your pen doesn't have autoprefixer turned on which is needed to add vendor prefixes. Try this:
http://codepen.io/jpdevries/pen/ZGrxLv

You can click the settings button in the CSS column and enable Autoprefixer for your pen

**Comment by lambert-velir** [comment]
The issue is with the background.  This is for a dropdown menu, so i need to be able to style the background ul as "shrinkwrapped" around the columns.

**Comment by jpdevries** [comment]
Ok. Do you see the effect of using autoprefixer has? That alone makes it wrap to two columns 
![](http://j4p.us/image/1W2Q46011p1m/Screen%20Shot%202015-07-02%20at%208.38.23%20AM.png)

**Comment by lambert-velir** [comment]
I do see that.  The <li>'s look like they're wrapping correctly, but the grey background (or any wrapper that I've tried) is only the height of the 2nd column, and isn't the width of both columns.

**Comment by jpdevries** [comment]
Oh I see what you're saying. I'm not sure whether or not that is a flexbox bug, but what about using CSS Columns instead?
http://codepen.io/jpdevries/pen/VLQXWJ

**Comment by lambert-velir** [comment]
Hmm, that is a possibility.  But the reason I wanted to use flexbox in the first place is that the number of menu items is dynamic.  We don't know how many there will be, so I wanted the dropdown to be 1 column if they fit, and they should overflow to a 2nd column if there are too many to fit in the max height.

**Comment by jpdevries** [comment]
Ya, that makes sense why you'd want to keep things flexible. How about this?
http://codepen.io/jpdevries/pen/vOdRpY

It isn't perfect. Without the `padding-bottom:1em` Safari has a little glitch. It looks like it isn't moving one of the items over to the next "column" correctly.

**Comment by philipwalton** [comment]
Yeah, this seems like a bug to me. If you look at the demo in Edge you'll notice it renders correctly.

**Comment by philipwalton** [comment]
I submitted this bug to Chrome:
https://code.google.com/p/chromium/issues/detail?id=507397

I can't really think of a good workaround for this, so I probably won't add it to the list in the README. If anyone else has any ideas, let me know.

**Comment by tylertadej** [comment]
This is the best solution I've found for this issue: http://stackoverflow.com/questions/39617628/height-of-flex-container-not-working-properly-in-safari

Wrap the ul in a flex div and apply the max-height there. Force the ul to have 100% width. Here is the same code revised: http://codepen.io/tylertadej/pen/VpWZgp

Unfortunately the suggestion provided on Jul 3, 2015 doesn't actually fix anything but only works for that specific amount of list items. The height was still being defaulting to the shortest column.

**Comment by Josh68** [comment]
Note that this is only a "fix" if your wrapper `div` either has a defined width or contained just within the body or any other block element within flow. If you have this situation nested within an absolutely positioned element (outside of normal flow), and you don't want to throw a defined width on the wrapper, I think there's really no fix.
