### ISSUE TITLE
About 11. Vertical, percentage-based padding and margins don't work on flex items.

### ISSUE THREAD

**Issue by raphaelgoetter** [philipwalton/flexbugs#67]
Actually, this is not a Firefox bug... but a Chrome / IE (others ?) bug.

The spec is misleading, see discussion here : https://twitter.com/CodingExon/status/617003128810921988

And Codepen here : http://codepen.io/raphaelgoetter/pen/EjQrWW?editors=110

**Comment by philipwalton** [comment]
Hmmm, thanks. Maybe it's worth just removing this bug until the spec is committed to one method or the other. And if Chrome is currently using the width for top/bottom padding/margin, I'm not sure there's a good way to workaround that.

**Comment by philipwalton** [comment]
Deleted via f236540830678d5be7c92e3e6299889359fdd76d.
