### ISSUE TITLE
Flexbox issue in chrome where widths aren't respected

### ISSUE THREAD

**Issue by fresheneesz** [philipwalton/flexbugs#68]
https://code.google.com/p/chromium/issues/detail?id=493020&can=4&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified

This causes weird things like checkboxes shrinking.

**Comment by philipwalton** [comment]
That's interesting. It seems like setting `flex: none` on the checkbox fixes the problem. I wonder if it has a default flex value other than that.

**Comment by fresheneesz** [comment]
Ooo, very nice work around. It also fixes the related case where a textbox will inexplicably grow when typed in, crowding out other elements. If you set `flex: none` on those elements being crowded out, it fixes the issue. If you want an item to have some kind of flexible growth/shrinkage, then obviously that workaround wouldn't work. But it works in my current cases, so thanks!

**Comment by philipwalton** [comment]
I'm going to close this for now because I think it's relatively easy to get around this by adding a width to the checkbox or its container. And I'm not sure it's common enough to go in the main list.

**Comment by fresheneesz** [comment]
Didn't realize they had to be common bugs. How can you tell how common it is? Adding explicit widths, tho, doesn't help in cases where you want flexible widths - IE one of the primary purposes of the flexbox. This doesn't only affect checkboxes.

**Comment by philipwalton** [comment]
My point is checkboxes are pretty standard sizes, so it's easy to add a width to a checkbox container and avoid this issue.

Don't worry about submitting the issue, I'm glad you did.

> How can you tell how common it is?

In the repo description I say this is a curated list, so on some level I have to apply my own judgment. I don't want the list to be overwhelming, so I have to exclude some things.

**Comment by fresheneesz** [comment]
hokay

**Comment by cbiesinger** [comment]
>  I wonder if it has a default flex value other than that.

Of course it does. The default flex value for everything is 0 1 auto.
