### ISSUE TITLE
`column` direction `flex-basis` discrepancies

### ISSUE THREAD

**Issue by byronmwong** [philipwalton/flexbugs#69]
http://jsbin.com/reqehosivi/1/edit?html,css,output

I have two elements stacked on top of each other in a flex layout. The parent doesn't have an explicit height, but I'd expect the parent to have the intrinsic height of the children. I noticed that different browsers behave differently depending on the value of `flex-basis`. In some cases, the parent renders with intrinsic height, in other cases, 0 height.

Whether the parent renders with intrinsic height:
```
Browser    | 0%  | 0px | auto |
Firefox    | yes | yes | yes
Safari     | no  | yes | yes
Chrome     | yes | no  | yes
IE (10/11) | no  | no  | yes

**Comment by philipwalton** [comment]
This is basically the same as Flexbug 1. At this point all released browsers except Firefox do not honor the default minimum content size of their flex items.

If you look at your demo in Edge and Chrome Canary, you'll see different results.

However, it looks like there may be a bug in Chrome Canary because it's still rendering the `0px` example as 0 pixels.

**Comment by byronmwong** [comment]
I agree this is related to Flexbug 1. One thing to note though is that `flex-shrink` is `0` in the demo, not `1`. So I guess I applied the "workaround" to Flexbug 1 to find that the "workaround" doesn't work in all browsers :frowning:

**Comment by philipwalton** [comment]
> So I guess I applied the "workaround" to Flexbug 1 to find that the "workaround" doesn't work in all browsers :frowning:

It does work, it just also needs to be paired with `flex-basis: auto` (that could probably be made more clear in the README). In your case, you're telling an element to be `0px` tall and then not to shrink. And that's exactly what all the browsers are doing.

**Comment by byronmwong** [comment]
ah that's starting to make more sense. I'm telling the elements to be 0px tall. Then I'm telling it each item to grow, but there's nowhere to grow.

However, Firefox doesn't fit that mental model because the container's height is the combined intrinsic heights of the children. So is Firefox right? Or are the other browsers right? Or is the behavior still undefined?

**Comment by philipwalton** [comment]
Column direction flex items do not grow unless the height of their container is definite. In your case, the container's height is not definite.

You can make it definite by setting the container to `display: flex` as I've done here:
http://jsbin.com/todizerexa/1/edit?html,css,output

**Comment by philipwalton** [comment]
I updated the language for flexbug 1 in e9f59e026d69c9f7d1afae34269579fd073356c1.

**Comment by byronmwong** [comment]
sweet, thanks for taking the time to explain it to me!
