### ISSUE TITLE
Firefox content effect block flex item 

### ISSUE THREAD

**Issue by idoros** [philipwalton/flexbugs#74]
http://jsbin.com/kenagerake/edit?html,output

Not sure what is the prefered behavior, but since the flex items are block elements, I would imagine that the content should not affect the the size of the flex item (like chrome and IE).

**Comment by philipwalton** [comment]
I think FF is correct in this case because flex items, by default, are not supposed to shrink to below their minimum content sizes, as mentioned in Flexbug 1.
