### ISSUE TITLE
Safari can't handle deeply nested flex boxes

### ISSUE THREAD

**Issue by adrianbw** [philipwalton/flexbugs#76]
As seen here: http://codepen.io/arbw/pen/xGPNrj . Safari seems to blow up when you nest a third level of flex boxes.

**Comment by philipwalton** [comment]
Can you clarify what you mean by "blow up"?

**Comment by adrianbw** [comment]
Yes, sorry, that was a lazy report and I should know better. :-/ 

Anyway, Safari seems to simply ignore flex declarations at the third level. In my pen, the words inside the buttons should be right-aligned:
<img width="777" alt="chrome flex demo" src="https://cloud.githubusercontent.com/assets/12662580/9390324/1c6db84a-4736-11e5-8b35-72d3075ea995.png">

But in Safari, we get this:
<img width="959" alt="safari flex demo" src="https://cloud.githubusercontent.com/assets/12662580/9390323/1c6d6e4e-4736-11e5-9198-e83bf3e4492a.png">

**Comment by philipwalton** [comment]
I don't think that has anything to do with the fact that the flex elements are nested. It's just that they're buttons. It's probably related to [flexbug 9](https://github.com/philipwalton/flexbugs#9-button-elements-cant-be-flex-containers).

**Comment by adrianbw** [comment]
I'm pretty sure we were getting this on regular divs, but I'll accept that I may be incorrect. Thanks!
