### ISSUE TITLE
lateral paddings in a input causes width miscalulation 

### ISSUE THREAD

**Issue by olivvv** [philipwalton/flexbugs#77]
the padding of an input causes miscalculation of that input's width

demo here:
http://codepen.io/Olivvv/pen/RPzbao?editors=110

example 3 demonstrate the broken state. Verified in chrome/mac, FF/mac.

**Comment by philipwalton** [comment]
I don't see a problem to here. Can you clarify? What do you expect to happen that's not happening?

**Comment by olivvv** [comment]
Example 3 demonstrates the bug. The correct behavior would be to have only one line.

In the example 3, the input field "pushes" the "stuff" element on a newline, because of its padding.
without padding (ex 2), they are on the same line as they should.
If it is any other element than input, with a padding (ex 4), they stay on the same line.
It is the combination input + padding that triggers the miscalculation.

I try more formally:
In a flex context, with flex-wrap:wrap, where there is 2 childs,
if one child has "flex: 1 0 auto;" and the other is default (so "flex: 0 1 auto;"),
then the second child will use the space necessary for its content,
and the first element will use the remaining space (if content permits).
agreed ?

Now this does not work anymore if the first element is an input and has a padding.

**Comment by philipwalton** [comment]
It's not true that the correct behavior for ex. 3 is to both be on the same line. Inputs have a default width, and when you add padding you increase the default width. This is difference from divs or spans which have no default width. That's why there's a difference.

**Comment by olivvv** [comment]
that makes sense, thanks for the explanation.
width: 0; on the input effectively provides the desired behavior.

Interestingly, when the container width is reduced, it goes on a newline when the width is :
secondChildWidth + firstChildPaddding + 3px
I imagine that 3px is the width of the carret in the input field
