### ISSUE TITLE
IE11 renders flex item height incorrectly, with column direction and 0% flex-basis

### ISSUE THREAD

**Issue by hanhpho** [philipwalton/flexbugs#78]
In IE11, direction: column, flex item basis 0%, the flex item height seems not automatically stretching along with the content height:

Demo: http://codepen.io/hanhpho/pen/KdPZOa?editors=110

Chrome:
<img width="487" alt="qqdjo" src="https://cloud.githubusercontent.com/assets/778442/9570962/9066e64e-4fc0-11e5-9e6d-ff220aa72b54.png">

IE11: 
![jxhcu](https://cloud.githubusercontent.com/assets/778442/9570965/9c03b55e-4fc0-11e5-996c-0dbcd2bf19cd.png)

If I set flex-basis to ``auto``, IE11 works fine. 
It seems a flexbox bug with IE11, anyone ran into the same thing?

**Comment by philipwalton** [comment]
I've seen this happen in several situation for IE, though I haven't gotten around to documenting it.

From what I can tell, this happens anytime you set a percentage `flex-basis` when the flex container's main size is indeterminate (meaning its size is based on the size of content), so it happens a lot for column flex containers, but it also happens for inline flex containers, floated flex containers, and nested flex containers.

The main solution/workaround/advice I have for now is to not use a relative `flex-basis` value (like a percentage) when the flex container's main size isn't definite.

**Comment by hanhpho** [comment]
I found the similar tracking issue here https://github.com/philipwalton/flexbugs/issues/58. Mark this as duplicated should be good :)
