### ISSUE TITLE
IE11 flex-direction: column bug

### ISSUE THREAD

**Issue by nicothin** [philipwalton/flexbugs#82]
http://codepen.io/nicothin/pen/dYPxjz?editors=110

**Comment by philipwalton** [comment]
You've provided no description, so it's hard for me to know what bug you're trying to report here, but at first glance, this is a duplcated of [flexbug 3](https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items).
