### ISSUE TITLE
Firefox don't calculate height for element with overflowing child

### ISSUE THREAD

**Issue by Ninerian** [philipwalton/flexbugs#89]
In my case a nested div construction with flexbox doesn't correctly calculate the height if it's set to auto. In chrome the box respects the borders of the wrapper element. In Firefox not.

Usecase for this bug.
http://codepen.io/Ninerian/pen/bVKqzz

**Comment by philipwalton** [comment]
This is another occurrence of Flexbug 1, which it looks like Chrome still has some kinks to work out.

If you add the following CSS to Firefox, you'll notice it renders as Chrome does:

```css
.wrapper-2 .c-1-2 {
  min-height: 0;
}
```

**Comment by Ninerian** [comment]
Thank you very much.
