### ISSUE TITLE
Safari performance extremely slow with nested flex-direction: column; boxes

### ISSUE THREAD

**Issue by krssctt** [philipwalton/flexbugs#96]
Performance suffers _greatly_ with multiple layers of column flex-boxes.  After 10 or so layers, each progressive layer causes 2x the delay from the previous layer.

Sample: http://codepen.io/anon/pen/YyOzMK?editors=001

**Comment by philipwalton** [comment]
Can you report this to webkit.org? And if you do, please post the link back here.

**Comment by krssctt** [comment]
One of my colleagues reported it recently:
https://bugs.webkit.org/show_bug.cgi?id=150445

**Comment by philipwalton** [comment]
Nice, thanks!
