### ISSUE TITLE
IE 11 - image as flex item

### ISSUE THREAD

**Issue by azinasili** [philipwalton/flexbugs#97]
When an image is a flex item IE seems to ignore the image's dimensions unless they are hard coded. Chrome and Firefox seems to handle images fine. I'm not sure if this is a bug since there is a work around, however in some cases hard coding the dimensions may not be an option. 

http://codepen.io/azinasili/pen/QjVaYB?editors=110

Would this be considered a bug? Or is there a different work around I have not discovered yet?

**Comment by jpdevries** [comment]
Could wrapping the images in a div (so the divs are the flex items) be considered another work around?

**Comment by azinasili** [comment]
I just tried it, wrapping the the image in a `div` does work. I hate that 'fix', however since it works I'm going to close the bug. If I find a more elegant solution I'll post it here.

**Comment by jpdevries** [comment]
FWIW I noticed that IE allows the image to grow really big even with

```css
.image {
  flex-grow:0;
}
```

**Comment by azinasili** [comment]
I have noticed that also, I'm pretty sure adding `min-height: 1px` solves this.
